/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.3 at Tue Apr 07 17:48:14 2020. */

#include "msgnode.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t BleParam_fields[6] = {
    PB_FIELD(  1, FLOAT   , OPTIONAL, STATIC  , FIRST, BleParam, bleInterval, bleInterval, 0),
    PB_FIELD(  2, SINT32  , OPTIONAL, STATIC  , OTHER, BleParam, bleTxp, bleInterval, 0),
    PB_FIELD(  3, UINT32  , OPTIONAL, STATIC  , OTHER, BleParam, bleOnTime, bleTxp, 0),
    PB_FIELD(  4, UINT32  , OPTIONAL, STATIC  , OTHER, BleParam, bleOffTime, bleOnTime, 0),
    PB_FIELD(  5, UINT32  , OPTIONAL, STATIC  , OTHER, BleParam, bleOnOff, bleOffTime, 0),
    PB_LAST_FIELD
};

const pb_field_t iBeacon_fields[5] = {
    PB_FIELD(  1, BYTES   , OPTIONAL, STATIC  , FIRST, iBeacon, uuid, uuid, 0),
    PB_FIELD(  2, UINT32  , OPTIONAL, STATIC  , OTHER, iBeacon, major, uuid, 0),
    PB_FIELD(  3, UINT32  , OPTIONAL, STATIC  , OTHER, iBeacon, minor, major, 0),
    PB_FIELD(  4, SINT32  , OPTIONAL, STATIC  , OTHER, iBeacon, mrssi, minor, 0),
    PB_LAST_FIELD
};

const pb_field_t AppParam_fields[2] = {
    PB_FIELD(  1, UENUM   , OPTIONAL, STATIC  , FIRST, AppParam, cmd, cmd, 0),
    PB_LAST_FIELD
};

const pb_field_t MsgNode_fields[9] = {
    PB_FIELD(  1, UINT32  , OPTIONAL, STATIC  , FIRST, MsgNode, id, id, 0),
    PB_FIELD(  2, UINT32  , OPTIONAL, STATIC  , OTHER, MsgNode, cmd, id, 0),
    PB_FIELD(  3, UINT32  , OPTIONAL, STATIC  , OTHER, MsgNode, cmdRet, cmd, 0),
    PB_FIELD(  5, MESSAGE , OPTIONAL, STATIC  , OTHER, MsgNode, bleParam, cmdRet, &BleParam_fields),
    PB_FIELD(  6, MESSAGE , OPTIONAL, STATIC  , OTHER, MsgNode, appParam, bleParam, &AppParam_fields),
    PB_FIELD( 38, MESSAGE , OPTIONAL, STATIC  , OTHER, MsgNode, ibeacon, appParam, &iBeacon_fields),
    PB_FIELD(200, UINT32  , OPTIONAL, STATIC  , OTHER, MsgNode, appBleFnt, ibeacon, 0),
    PB_FIELD(201, UINT32  , OPTIONAL, STATIC  , OTHER, MsgNode, appLowPowerLevel, appBleFnt, 0),
    PB_LAST_FIELD
};



/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(MsgNode, bleParam) < 65536 && pb_membersize(MsgNode, appParam) < 65536 && pb_membersize(MsgNode, ibeacon) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_BleParam_iBeacon_AppParam_MsgNode)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(MsgNode, bleParam) < 256 && pb_membersize(MsgNode, appParam) < 256 && pb_membersize(MsgNode, ibeacon) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_BleParam_iBeacon_AppParam_MsgNode)
#endif


/* @@protoc_insertion_point(eof) */
